publish_world_models:
    ros__parameters:
        meshes:
            seafloor:
                plane: [200., 200., 0.1]
                pose:
                    position: [-100., 0., -50.]
            north:
                plane: [0.1, 200., 50.]
                pose:
                    position: [0., 0., -25.]
            south:
                plane: [0.1, 200., 50.]
                pose:
                    position: [-200., 0., -25.]
            west:
                plane: [200., 0.1, 50.]
                pose:
                    position: [-100., -100., -25.]
            east:
                plane: [200., 0.1, 50.]
                pose:
                    position: [-100., 100., -25.]